stages:
  - build

before_script:
  - if [ -n "$CI_COMMIT_TAG" ]; then
    export VERSIONING_GIT_TAG=$CI_COMMIT_TAG;
    else
    export VERSIONING_GIT_BRANCH=$CI_COMMIT_REF_NAME;
    fi
  - "let BUILD_NUMBER=CI_PIPELINE_IID"
  - "export BUILD_NUMBER"
  - "echo 'Build: '$BUILD_NUMBER"
  - "export logbackDisableServletContainerInitializer=true"
  - "mkdir -p $CI_PROJECT_DIR/.m2"

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GITLAB_DEPLOY_TOKEN: ${DEPLOY_TOKEN}
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

services:
  - docker:27.2.0-dind

################################################################################
maven-build:
  stage: build
  script:
    - "cp ./.mvn/ci-settings.xml $CI_PROJECT_DIR/.m2/settings.xml"
    - "mvn -P ci clean deploy -s $CI_PROJECT_DIR/.m2/settings.xml"
  tags:
    - common-ci
