sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
before_install:
  - cp ./.mvn/ci-settings.xml $HOME/.m2/settings.xml

script: "mvn -P ci install"

deploy:
  provider: script
  script: "mvn -P ci deploy"
  skip_cleanup: false
  condition: "$TRAVIS_TAG = ^v.*$"
  on:
    tags: true
